// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.5
// source: api/api.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CreateWheelReq fields to create a wheel of fortune
type CreateWheelReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Segments []int64 `protobuf:"varint,2,rep,packed,name=segments,proto3" json:"segments,omitempty"`
}

func (x *CreateWheelReq) Reset() {
	*x = CreateWheelReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateWheelReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWheelReq) ProtoMessage() {}

func (x *CreateWheelReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWheelReq.ProtoReflect.Descriptor instead.
func (*CreateWheelReq) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{0}
}

func (x *CreateWheelReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateWheelReq) GetSegments() []int64 {
	if x != nil {
		return x.Segments
	}
	return nil
}

// CreateWheelReq fields represent the response of the creation
// of a wheel of fortune
type CreateWheelResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *CreateWheelResp) Reset() {
	*x = CreateWheelResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateWheelResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWheelResp) ProtoMessage() {}

func (x *CreateWheelResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWheelResp.ProtoReflect.Descriptor instead.
func (*CreateWheelResp) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{1}
}

func (x *CreateWheelResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// CreateWheelReq fields to create a wheel of fortune
type SpinWheelReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *SpinWheelReq) Reset() {
	*x = SpinWheelReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpinWheelReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpinWheelReq) ProtoMessage() {}

func (x *SpinWheelReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpinWheelReq.ProtoReflect.Descriptor instead.
func (*SpinWheelReq) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{2}
}

func (x *SpinWheelReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// CreateWheelReq fields represent the response of the creation
// of a wheel of fortune
type SpinWheelResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WinningSegmentIndex int64  `protobuf:"varint,1,opt,name=winningSegmentIndex,proto3" json:"winningSegmentIndex,omitempty"`
	RemainingPrizes     int64  `protobuf:"varint,2,opt,name=remainingPrizes,proto3" json:"remainingPrizes,omitempty"`
	Error               string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *SpinWheelResp) Reset() {
	*x = SpinWheelResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpinWheelResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpinWheelResp) ProtoMessage() {}

func (x *SpinWheelResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpinWheelResp.ProtoReflect.Descriptor instead.
func (*SpinWheelResp) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{3}
}

func (x *SpinWheelResp) GetWinningSegmentIndex() int64 {
	if x != nil {
		return x.WinningSegmentIndex
	}
	return 0
}

func (x *SpinWheelResp) GetRemainingPrizes() int64 {
	if x != nil {
		return x.RemainingPrizes
	}
	return 0
}

func (x *SpinWheelResp) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// WheelStatusReq fields to get the status of a wheel of fortune
type WheelStatusReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *WheelStatusReq) Reset() {
	*x = WheelStatusReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_api_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WheelStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WheelStatusReq) ProtoMessage() {}

func (x *WheelStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WheelStatusReq.ProtoReflect.Descriptor instead.
func (*WheelStatusReq) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{4}
}

func (x *WheelStatusReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// WheelStatusResp fields represent the response of state
// of a wheel of fortune
type WheelStatusResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Spins   int64   `protobuf:"varint,1,opt,name=spins,proto3" json:"spins,omitempty"`
	Prizes  []int64 `protobuf:"varint,2,rep,packed,name=prizes,proto3" json:"prizes,omitempty"`
	Enabled bool    `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"`
}

func (x *WheelStatusResp) Reset() {
	*x = WheelStatusResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_api_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WheelStatusResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WheelStatusResp) ProtoMessage() {}

func (x *WheelStatusResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WheelStatusResp.ProtoReflect.Descriptor instead.
func (*WheelStatusResp) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{5}
}

func (x *WheelStatusResp) GetSpins() int64 {
	if x != nil {
		return x.Spins
	}
	return 0
}

func (x *WheelStatusResp) GetPrizes() []int64 {
	if x != nil {
		return x.Prizes
	}
	return nil
}

func (x *WheelStatusResp) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type GetAllWheelnamesReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetAllWheelnamesReq) Reset() {
	*x = GetAllWheelnamesReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_api_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllWheelnamesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllWheelnamesReq) ProtoMessage() {}

func (x *GetAllWheelnamesReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllWheelnamesReq.ProtoReflect.Descriptor instead.
func (*GetAllWheelnamesReq) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{6}
}

type GetAllWheelnamesResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Wheels []string `protobuf:"bytes,1,rep,name=wheels,proto3" json:"wheels,omitempty"`
}

func (x *GetAllWheelnamesResp) Reset() {
	*x = GetAllWheelnamesResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_api_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllWheelnamesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllWheelnamesResp) ProtoMessage() {}

func (x *GetAllWheelnamesResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllWheelnamesResp.ProtoReflect.Descriptor instead.
func (*GetAllWheelnamesResp) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{7}
}

func (x *GetAllWheelnamesResp) GetWheels() []string {
	if x != nil {
		return x.Wheels
	}
	return nil
}

var File_api_api_proto protoreflect.FileDescriptor

var file_api_api_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x06, 0x67, 0x6f, 0x70, 0x68, 0x65, 0x72, 0x22, 0x40, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x57, 0x68, 0x65, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x03, 0x52,
	0x08, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x2b, 0x0a, 0x0f, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x57, 0x68, 0x65, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x22, 0x0a, 0x0c, 0x53, 0x70, 0x69, 0x6e, 0x57, 0x68,
	0x65, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x81, 0x01, 0x0a, 0x0d, 0x53,
	0x70, 0x69, 0x6e, 0x57, 0x68, 0x65, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x12, 0x30, 0x0a, 0x13,
	0x77, 0x69, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x6e,
	0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x13, 0x77, 0x69, 0x6e, 0x6e, 0x69,
	0x6e, 0x67, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x28,
	0x0a, 0x0f, 0x72, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x50, 0x72, 0x69, 0x7a, 0x65,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0f, 0x72, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x69,
	0x6e, 0x67, 0x50, 0x72, 0x69, 0x7a, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x24,
	0x0a, 0x0e, 0x57, 0x68, 0x65, 0x65, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x22, 0x59, 0x0a, 0x0f, 0x57, 0x68, 0x65, 0x65, 0x6c, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x70, 0x69, 0x6e, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x73, 0x70, 0x69, 0x6e, 0x73, 0x12, 0x16, 0x0a,
	0x06, 0x70, 0x72, 0x69, 0x7a, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x03, 0x52, 0x06, 0x70,
	0x72, 0x69, 0x7a, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x22,
	0x15, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x57, 0x68, 0x65, 0x65, 0x6c, 0x6e, 0x61,
	0x6d, 0x65, 0x73, 0x52, 0x65, 0x71, 0x22, 0x2e, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c,
	0x57, 0x68, 0x65, 0x65, 0x6c, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x16,
	0x0a, 0x06, 0x77, 0x68, 0x65, 0x65, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06,
	0x77, 0x68, 0x65, 0x65, 0x6c, 0x73, 0x32, 0x9b, 0x02, 0x0a, 0x05, 0x57, 0x68, 0x65, 0x65, 0x6c,
	0x12, 0x40, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x57, 0x68, 0x65, 0x65, 0x6c, 0x12,
	0x16, 0x2e, 0x67, 0x6f, 0x70, 0x68, 0x65, 0x72, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x57,
	0x68, 0x65, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x1a, 0x17, 0x2e, 0x67, 0x6f, 0x70, 0x68, 0x65, 0x72,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x57, 0x68, 0x65, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70,
	0x22, 0x00, 0x12, 0x3a, 0x0a, 0x09, 0x53, 0x70, 0x69, 0x6e, 0x57, 0x68, 0x65, 0x65, 0x6c, 0x12,
	0x14, 0x2e, 0x67, 0x6f, 0x70, 0x68, 0x65, 0x72, 0x2e, 0x53, 0x70, 0x69, 0x6e, 0x57, 0x68, 0x65,
	0x65, 0x6c, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x67, 0x6f, 0x70, 0x68, 0x65, 0x72, 0x2e, 0x53,
	0x70, 0x69, 0x6e, 0x57, 0x68, 0x65, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x43,
	0x0a, 0x0e, 0x47, 0x65, 0x74, 0x57, 0x68, 0x65, 0x65, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x16, 0x2e, 0x67, 0x6f, 0x70, 0x68, 0x65, 0x72, 0x2e, 0x57, 0x68, 0x65, 0x65, 0x6c, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x17, 0x2e, 0x67, 0x6f, 0x70, 0x68, 0x65,
	0x72, 0x2e, 0x57, 0x68, 0x65, 0x65, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x22, 0x00, 0x12, 0x4f, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x57, 0x68, 0x65,
	0x65, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x12, 0x1b, 0x2e, 0x67, 0x6f, 0x70, 0x68, 0x65, 0x72,
	0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x57, 0x68, 0x65, 0x65, 0x6c, 0x6e, 0x61, 0x6d, 0x65,
	0x73, 0x52, 0x65, 0x71, 0x1a, 0x1c, 0x2e, 0x67, 0x6f, 0x70, 0x68, 0x65, 0x72, 0x2e, 0x47, 0x65,
	0x74, 0x41, 0x6c, 0x6c, 0x57, 0x68, 0x65, 0x65, 0x6c, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x22, 0x00, 0x42, 0x1d, 0x5a, 0x1b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x6a, 0x61, 0x63, 0x6b, 0x6d, 0x63, 0x67, 0x75, 0x69, 0x72, 0x65, 0x31, 0x2f,
	0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_api_proto_rawDescOnce sync.Once
	file_api_api_proto_rawDescData = file_api_api_proto_rawDesc
)

func file_api_api_proto_rawDescGZIP() []byte {
	file_api_api_proto_rawDescOnce.Do(func() {
		file_api_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_api_proto_rawDescData)
	})
	return file_api_api_proto_rawDescData
}

var file_api_api_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_api_proto_goTypes = []interface{}{
	(*CreateWheelReq)(nil),       // 0: gopher.CreateWheelReq
	(*CreateWheelResp)(nil),      // 1: gopher.CreateWheelResp
	(*SpinWheelReq)(nil),         // 2: gopher.SpinWheelReq
	(*SpinWheelResp)(nil),        // 3: gopher.SpinWheelResp
	(*WheelStatusReq)(nil),       // 4: gopher.WheelStatusReq
	(*WheelStatusResp)(nil),      // 5: gopher.WheelStatusResp
	(*GetAllWheelnamesReq)(nil),  // 6: gopher.GetAllWheelnamesReq
	(*GetAllWheelnamesResp)(nil), // 7: gopher.GetAllWheelnamesResp
}
var file_api_api_proto_depIdxs = []int32{
	0, // 0: gopher.Wheel.CreateWheel:input_type -> gopher.CreateWheelReq
	2, // 1: gopher.Wheel.SpinWheel:input_type -> gopher.SpinWheelReq
	4, // 2: gopher.Wheel.GetWheelStatus:input_type -> gopher.WheelStatusReq
	6, // 3: gopher.Wheel.GetAllWheelNames:input_type -> gopher.GetAllWheelnamesReq
	1, // 4: gopher.Wheel.CreateWheel:output_type -> gopher.CreateWheelResp
	3, // 5: gopher.Wheel.SpinWheel:output_type -> gopher.SpinWheelResp
	5, // 6: gopher.Wheel.GetWheelStatus:output_type -> gopher.WheelStatusResp
	7, // 7: gopher.Wheel.GetAllWheelNames:output_type -> gopher.GetAllWheelnamesResp
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_api_proto_init() }
func file_api_api_proto_init() {
	if File_api_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateWheelReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateWheelResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpinWheelReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpinWheelResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_api_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WheelStatusReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_api_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WheelStatusResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_api_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllWheelnamesReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_api_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllWheelnamesResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_api_proto_goTypes,
		DependencyIndexes: file_api_api_proto_depIdxs,
		MessageInfos:      file_api_api_proto_msgTypes,
	}.Build()
	File_api_api_proto = out.File
	file_api_api_proto_rawDesc = nil
	file_api_api_proto_goTypes = nil
	file_api_api_proto_depIdxs = nil
}
